# Generated by Django 5.2.3 on 2025-07-01 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptify_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
